### ISSUE TITLE
Not being pinged when people @ me......

### ISSUE THREAD

**Issue by bentenz5** [tgicn/NightcoreIssues#12]
It would appear that since Plug shut down, pinging is borked. It just doesnt ping anymore. Likely because Plug deleted they're entire site, as noticed by attempting to navigate to cdn.plug.dj no longer gives an unauthorized error.

**Comment by Foorack** [comment]
Thanks for reporting it! We have found the problem and it will be fixed as soon as TBH wakes up. I will wait with closing this until it's actually fixed.

**Comment by Foorack** [comment]
Hellu again! The problem seems to be with some DNS servers in some geographical areas around the world. To fix this we recommend you to use Google's DNS server. More information on how to switch can be found here:

https://developers.google.com/speed/public-dns/docs/using?hl=en

Because this is a problem outside our control and a fix exists I will mark this as closed. Feel free to comment here to reopen in if switching to Google DNS does not solve the issue. :smiley:

**Comment by bentenz5** [comment]
Swapped to Google DNS, fixed the problem! Thanks @Foorack
