### ISSUE TITLE
Mention @everyone

### ISSUE THREAD

**Issue by Foorack** [tgicn/NightcoreIssues#19]
My idea is to implement a @ everyone and possibly @ staff. This would have to be a feature only available to staff as it could easily be abused. :smile:

**Comment by Grengras** [comment]
Definitely not something that should slip into the grasps of ordinary mortals such as myself. *pictures the 'fun' random people would have with that if it was public access and shudders*

But I also agree it is something that could be useful for staff purposes. For example the @ staff option could be used by a resident dj or bouncer to get a higher level access member's attention to a song playing that needs a perma BLed due to NSFW or theme / etc.

**Comment by Foorack** [comment]
Done.
